In [16]:
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
from sqlalchemy import create_engine, inspect, func
from config import key

In [17]:
file = "2015.csv"
df2015 = pd.read_csv(file)
df2015.head()

       Country          Region  Happiness Rank  Happiness Score  Standard Error  Economy (GDP per Capita)   Family  Health (Life Expectancy)  Freedom  Trust (Government Corruption)  Generosity  Dystopia Residual
0  Switzerland  Western Europe               1            7.587         0.03411                   1.39651  1.34951                   0.94143  0.66557                        0.41978     0.29678            2.51738
1      Iceland  Western Europe               2            7.561         0.04884                   1.30232  1.40223                   0.94784  0.62877                        0.14145     0.43630            2.70201
2      Denmark  Western Europe               3            7.527         0.03328                   1.32548  1.36058                   0.87464  0.64938                        0.48357     0.34139            2.49204
3       Norway  Western Europe               4            7.522         0.03880                   1.45900  1.33095                   0.88521  0.66973                        0.36503     0.34699            2.46531
4       Canada   North America               5            7.427         0.03553                   1.32629  1.32261                   0.90563  0.63297                        0.32957     0.45811            2.45176

In [18]:
file = "2020.csv"
df2020 = pd.read_csv(file)
df2020.head()

  Country name Regional indicator  Ladder score  Standard error of ladder score  upperwhisker  lowerwhisker  Logged GDP per capita  Social support  Healthy life expectancy  Freedom to make life choices  Generosity  Perceptions of corruption  Ladder score in Dystopia  Explained by: Log GDP per capita  Explained by: Social support  Explained by: Healthy life expectancy  Explained by: Freedom to make life choices  Explained by: Generosity  Explained by: Perceptions of corruption  Dystopia + residual
0      Finland     Western Europe        7.8087                        0.031156      7.869766      7.747634              10.639267        0.954330                71.900825                      0.949172   -0.059482                   0.195445                  1.972317                          1.285190                      1.499526                               0.961271                                    0.662317                  0.159670                                 0.477857             2.762835
1      Denmark     Western Europe        7.6456                        0.033492      7.711245      7.579955              10.774001        0.955991                72.402504                      0.951444    0.066202                   0.168489                  1.972317                          1.326949                      1.503449                               0.979333                                    0.665040                  0.242793                                 0.495260             2.432741
2  Switzerland     Western Europe        7.5599                        0.035014      7.628528      7.491272              10.979933        0.942847                74.102448                      0.921337    0.105911                   0.303728                  1.972317                          1.390774                      1.472403                               1.040533                                    0.628954                  0.269056                                 0.407946             2.350267
3      Iceland     Western Europe        7.5045                        0.059616      7.621347      7.387653              10.772559        0.974670                73.000000                      0.948892    0.246944                   0.711710                  1.972317                          1.326502                      1.547567                               1.000843                                    0.661981                  0.362330                                 0.144541             2.460688
4       Norway     Western Europe        7.4880                        0.034837      7.556281      7.419719              11.087804        0.952487                73.200783                      0.955750    0.134533                   0.263218                  1.972317                          1.424207                      1.495173                               1.008072                                    0.670201                  0.287985                                 0.434101             2.168266

In [19]:
# display 2015 columns

df2015.columns

Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score', 'Standard Error', 'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)', 'Generosity', 'Dystopia Residual'], dtype='object')

In [20]:
# drop unwanted columns from 2015 df

dropped2015 = df2015.drop(columns =['Region','Standard Error', 'Economy (GDP per Capita)', 'Family','Freedom', 'Dystopia Residual'])
dropped2015.head()

       Country  Happiness Rank  Happiness Score  Health (Life Expectancy)  Trust (Government Corruption)  Generosity
0  Switzerland               1            7.587                   0.94143                        0.41978     0.29678
1      Iceland               2            7.561                   0.94784                        0.14145     0.43630
2      Denmark               3            7.527                   0.87464                        0.48357     0.34139
3       Norway               4            7.522                   0.88521                        0.36503     0.34699
4       Canada               5            7.427                   0.90563                        0.32957     0.45811

In [21]:
# display 2020 df columns

df2020.columns

Index(['Country name', 'Regional indicator', 'Ladder score', 'Standard error of ladder score', 'upperwhisker', 'lowerwhisker', 'Logged GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption', 'Ladder score in Dystopia', 'Explained by: Log GDP per capita', 'Explained by: Social support', 'Explained by: Healthy life expectancy', 'Explained by: Freedom to make life choices', 'Explained by: Generosity', 'Explained by: Perceptions of corruption', 'Dystopia + residual'], dtype='object')

In [22]:
# drop unwanted columns from 2020 df

dropped2020 = df2020.drop(columns = ['Regional indicator', 
       'Standard error of ladder score', 'upperwhisker', 'lowerwhisker',
       'Logged GDP per capita', 'Social support', 
       'Freedom to make life choices',
       'Ladder score in Dystopia',
       'Explained by: Log GDP per capita', 'Explained by: Social support',
       'Explained by: Healthy life expectancy',
       'Explained by: Freedom to make life choices',
       'Explained by: Generosity', 'Explained by: Perceptions of corruption',
       'Dystopia + residual'])
dropped2020.head()

  Country name  Ladder score  Healthy life expectancy  Generosity  Perceptions of corruption
0      Finland        7.8087                71.900825   -0.059482                   0.195445
1      Denmark        7.6456                72.402504    0.066202                   0.168489
2  Switzerland        7.5599                74.102448    0.105911                   0.303728
3      Iceland        7.5045                73.000000    0.246944                   0.711710
4       Norway        7.4880                73.200783    0.134533                   0.263218

In [23]:
# rename columns in 2015 dropped df

dropped2015_transformed = dropped2015.rename(columns={"Country": "country", 
                                                      "Happiness Rank": "happiness_rank_2015", 
                                                      "Happiness Score": "happiness_score_2015",
                                                          "Health (Life Expectancy)": "life_expectancy_2015",
                                                          "Generosity": "generosity_2015", "Trust (Government Corruption)": "trust_2015"})


dropped2015_ordered = dropped2015_transformed[["country", "happiness_rank_2015", "happiness_score_2015", "life_expectancy_2015", "generosity_2015", "trust_2015"]]
dropped2015_ordered.head()

       country  happiness_rank_2015  happiness_score_2015  life_expectancy_2015  generosity_2015  trust_2015
0  Switzerland                    1                 7.587               0.94143          0.29678     0.41978
1      Iceland                    2                 7.561               0.94784          0.43630     0.14145
2      Denmark                    3                 7.527               0.87464          0.34139     0.48357
3       Norway                    4                 7.522               0.88521          0.34699     0.36503
4       Canada                    5                 7.427               0.90563          0.45811     0.32957

In [24]:
# rename columns in 2020 dropped df

dropped2020_transformed = dropped2020.rename(columns={"Country name": "country", 
                                                      "Ladder score": "happiness_score_2020",
                                                        "Healthy life expectancy": "life_expectancy_2020",
                                                          "Generosity": "generosity_2020",
                                                          "Perceptions of corruption": "trust_2020"})
dropped2020_transformed.head()

       country  happiness_score_2020  life_expectancy_2020  generosity_2020  trust_2020
0      Finland                7.8087             71.900825        -0.059482    0.195445
1      Denmark                7.6456             72.402504         0.066202    0.168489
2  Switzerland                7.5599             74.102448         0.105911    0.303728
3      Iceland                7.5045             73.000000         0.246944    0.711710
4       Norway                7.4880             73.200783         0.134533    0.263218

In [25]:
merged_df = pd.merge(dropped2015_ordered, dropped2020_transformed, on="country", how="outer")
merged_df.head(158)

                      country  happiness_rank_2015  happiness_score_2015  life_expectancy_2015  generosity_2015  trust_2015  happiness_score_2020  life_expectancy_2020  generosity_2020  trust_2020
0                 Switzerland                  1.0                 7.587               0.94143          0.29678     0.41978                7.5599             74.102448         0.105911    0.303728
1                     Iceland                  2.0                 7.561               0.94784          0.43630     0.14145                7.5045             73.000000         0.246944    0.711710
2                     Denmark                  3.0                 7.527               0.87464          0.34139     0.48357                7.6456             72.402504         0.066202    0.168489
3                      Norway                  4.0                 7.522               0.88521          0.34699     0.36503                7.4880             73.200783         0.134533    0.263218
4                      Canada                  5.0                 7.427               0.90563          0.45811     0.32957                7.2321             73.601601         0.124771    0.390843
5                     Finland                  6.0                 7.406               0.88911          0.23351     0.41372                7.8087             71.900825        -0.059482    0.195445
6                 Netherlands                  7.0                 7.378               0.89284          0.47610     0.31814                7.4489             72.300919         0.207612    0.364717
7                      Sweden                  8.0                 7.364               0.91087          0.36262     0.43844                7.3535             72.600769         0.111615    0.250880
8                 New Zealand                  9.0                 7.286               0.90837          0.47501     0.42922                7.2996             73.202629         0.191598    0.221139
9                   Australia                 10.0                 7.284               0.93156          0.43562     0.35637                7.2228             73.604538         0.190460    0.415169
10                     Israel                 11.0                 7.278               0.91387          0.33172     0.07785                7.1286             73.200256         0.102594    0.780855
11                 Costa Rica                 12.0                 7.226               0.86027          0.25497     0.10583                7.1214             71.299850        -0.102430    0.786332
12                    Austria                 13.0                 7.200               0.89042          0.33088     0.18676                7.2942             73.002502         0.085429    0.499955
13                     Mexico                 14.0                 7.187               0.81444          0.14074     0.21312                6.4650             68.299026        -0.175267    0.806822
14              United States                 15.0                 7.119               0.86179          0.40105     0.15890                6.9396             68.299500         0.149892    0.699715
15                     Brazil                 16.0                 6.983               0.69702          0.14574     0.17521                6.3756             66.480164        -0.101812    0.770601
16                 Luxembourg                 17.0                 6.946               0.91894          0.28034     0.37798                7.2375             72.599998        -0.004621    0.367084
17                    Ireland                 18.0                 6.940               0.89533          0.45901     0.28703                7.0937             72.300789         0.145785    0.357184
18                    Belgium                 19.0                 6.937               0.89667          0.22250     0.22540                6.8635             72.001648        -0.078691    0.612298
19       United Arab Emirates                 20.0                 6.901               0.80925          0.26428     0.38583                6.7908             67.082787         0.123451    0.594502
20             United Kingdom                 21.0                 6.867               0.90943          0.51912     0.32067                7.1645             72.301605         0.263732    0.435916
21                       Oman                 22.0                 6.853               0.76276          0.21542     0.32524                   NaN                   NaN              NaN         NaN
22                  Venezuela                 23.0                 6.810               0.72052          0.05841     0.11069                5.0532             66.505341        -0.169091    0.837038
23                  Singapore                 24.0                 6.798               1.02525          0.31105     0.49210                6.3771             76.804581         0.029879    0.109784
24                     Panama                 25.0                 6.786               0.79661          0.24434     0.09270                6.3048             69.603012        -0.153928    0.851589
25                    Germany                 26.0                 6.750               0.89186          0.28214     0.21843                7.0758             72.202019         0.080179    0.456422
26                      Chile                 27.0                 6.670               0.85857          0.33363     0.12869                6.2285             69.900620        -0.065668    0.838239
27                      Qatar                 28.0                 6.611               0.79733          0.32573     0.52208                   NaN                   NaN              NaN         NaN
28                     France                 29.0                 6.575               0.94579          0.12332     0.20646                6.6638             73.801933        -0.130642    0.583521
29                  Argentina                 30.0                 6.574               0.78723          0.11451     0.08484                5.9747             68.803802        -0.194914    0.842010
30             Czech Republic                 31.0                 6.505               0.84483          0.10686     0.02652                6.9109             70.047935        -0.230862    0.858446
31                    Uruguay                 32.0                 6.485               0.81160          0.23240     0.24558                6.4401             69.002548        -0.101103    0.635994
32                   Colombia                 33.0                 6.477               0.69077          0.18401     0.05120                6.1634             67.699585        -0.161236    0.864572
33                   Thailand                 34.0                 6.455               0.73850          0.57630     0.03187                5.9988             67.250595         0.268685    0.886272
34               Saudi Arabia                 35.0                 6.411               0.72025          0.13706     0.32524                6.4065             66.305145        -0.168695    0.682620
35                      Spain                 36.0                 6.329               0.95562          0.18227     0.06398                6.4009             74.402710        -0.050962    0.765860
36                      Malta                 37.0                 6.302               0.88721          0.51752     0.13586                6.7728             72.199997         0.214966    0.658547
37                     Taiwan                 38.0                 6.298               0.87530          0.25376     0.08129                   NaN                   NaN              NaN         NaN
38                     Kuwait                 39.0                 6.295               0.72492          0.16228     0.25609                6.1021             66.767647        -0.100185    0.760849
39                   Suriname                 40.0                 6.269               0.60820          0.16991     0.13633                   NaN                   NaN              NaN         NaN
40        Trinidad and Tobago                 41.0                 6.168               0.61483          0.31844     0.01140                6.1919             63.500000         0.000527    0.912231
41                El Salvador                 42.0                 6.130               0.67737          0.10692     0.11776                6.3483             66.108261        -0.121073    0.754320
42                  Guatemala                 43.0                 6.123               0.64425          0.27489     0.09472                6.3989             64.808945        -0.042939    0.783237
43                 Uzbekistan                 44.0                 6.003               0.59772          0.22837     0.30826                6.2576             65.107574         0.248427    0.501497
44                   Slovakia                 45.0                 5.995               0.78902          0.16893     0.03431                6.2806             68.906342        -0.124409    0.918096
45                      Japan                 46.0                 5.987               0.99111          0.10705     0.18060                5.8708             75.000969        -0.246910    0.654558
46                South Korea                 47.0                 5.984               0.96538          0.18557     0.07857                5.8724             73.602730        -0.043404    0.789067
47                    Ecuador                 48.0                 5.975               0.79075          0.11541     0.18090                5.9252             68.500038        -0.127015    0.801215
48                    Bahrain                 49.0                 5.960               0.74716          0.17362     0.30600                6.2273             68.500000         0.133729    0.739347
49                      Italy                 50.0                 5.948               0.95446          0.22823     0.02901                6.3874             73.601685        -0.043461    0.873405
50                    Bolivia                 51.0                 5.890               0.53920          0.20536     0.08800                5.7475             63.600471        -0.091681    0.822606
51                    Moldova                 52.0                 5.889               0.61826          0.20951     0.01615                5.6075             65.013016        -0.037741    0.913314
52                   Paraguay                 53.0                 5.878               0.66098          0.34240     0.08242                5.6921             65.639938         0.007998    0.834789
53                 Kazakhstan                 54.0                 5.855               0.64368          0.11827     0.08454                6.0579             64.609962        -0.068489    0.764491
54                   Slovenia                 55.0                 5.848               0.87337          0.25328     0.03787                6.3634             71.102989        -0.080603    0.817071
55                  Lithuania                 56.0                 5.833               0.73128          0.02641     0.01031                6.2155             67.294075        -0.219725    0.809584
56                  Nicaragua                 57.0                 5.828               0.74314          0.27815     0.19317                6.1371             67.507179         0.020959    0.665950
57                       Peru                 58.0                 5.824               0.73017          0.14982     0.05989                5.7968             68.100235        -0.162388    0.893715
58                    Belarus                 59.0                 5.813               0.73608          0.11046     0.19090                5.5399             66.104332        -0.164927    0.635712
59                     Poland                 60.0                 5.791               0.77903          0.16759     0.04212                6.1863             69.311134        -0.205084    0.686927
60                   Malaysia                 61.0                 5.770               0.72394          0.33075     0.10501                5.3843             67.102158         0.114727    0.839302
61                    Croatia                 62.0                 5.759               0.78805          0.05444     0.02430                5.5047             70.214905        -0.128538    0.916495
62                      Libya                 63.0                 5.754               0.70380          0.18295     0.11023                5.4888             62.299999        -0.085054    0.668779
63                     Russia                 64.0                 5.716               0.66926          0.00199     0.03005                5.5460             64.100456        -0.151154    0.864803
64                    Jamaica                 65.0                 5.709               0.68741          0.21230     0.02299                5.8898             67.099998        -0.125107    0.888890
65               North Cyprus                 66.0                 5.695               0.92356          0.26169     0.14280                5.5355             73.702225         0.000227    0.626116
66                     Cyprus                 67.0                 5.689               0.92356          0.30638     0.06146                6.1590             73.702225         0.043731    0.856272
67                    Algeria                 68.0                 5.605               0.61766          0.07822     0.17383                5.0051             65.905174        -0.121105    0.735485
68                     Kosovo                 69.0                 5.589               0.63132          0.28310     0.04741                6.3252             63.885555         0.190934    0.922328
69               Turkmenistan                 70.0                 5.548               0.53886          0.16979     0.30844                5.1191             62.211708         0.187672    0.883692
70                  Mauritius                 71.0                 5.477               0.70950          0.37744     0.07521                6.1013             66.404343        -0.018319    0.805343
71                  Hong Kong                 72.0                 5.474               1.01328          0.39478     0.37124                   NaN                   NaN              NaN         NaN
72                    Estonia                 73.0                 5.429               0.77361          0.08680     0.15184                6.0218             68.604958        -0.111698    0.623074
73                  Indonesia                 74.0                 5.399               0.63793          0.51535     0.00000                5.2856             62.155849         0.519587    0.876296
74                    Vietnam                 75.0                 5.360               0.74676          0.16860     0.10441                5.3535             67.952736        -0.094533    0.796421
75                     Turkey                 76.0                 5.332               0.73172          0.12253     0.15746                5.1318             66.902817        -0.171046    0.748197
76                 Kyrgyzstan                 77.0                 5.286               0.65088          0.30030     0.04232                5.5415             64.106010         0.154772    0.888396
77                    Nigeria                 78.0                 5.268               0.16007          0.27233     0.04030                4.7241             49.861908         0.033746    0.861874
78                     Bhutan                 79.0                 5.253               0.57407          0.47998     0.15445                   NaN                   NaN              NaN         NaN
79                 Azerbaijan                 80.0                 5.212               0.64045          0.07799     0.16065                5.1648             65.508400        -0.240255    0.552538
80                   Pakistan                 81.0                 5.194               0.51466          0.33671     0.10464                5.6933             58.253136         0.044900    0.745705
81                     Jordan                 82.0                 5.192               0.69639          0.11053     0.14293                4.6334             66.799751        -0.162565    0.700344
82                 Montenegro                 82.0                 5.192               0.72521          0.16140     0.14296                5.5461             68.505348        -0.075600    0.783122
83                      China                 84.0                 5.140               0.81658          0.08185     0.02781                5.1239             69.289192        -0.181426    0.753971
84                     Zambia                 85.0                 5.129               0.29924          0.19591     0.12468                3.7594             55.299377         0.078037    0.801290
85                    Romania                 86.0                 5.124               0.76890          0.13748     0.00649                6.1237             67.207237        -0.197815    0.934300
86                     Serbia                 87.0                 5.123               0.74836          0.19231     0.02617                5.7782             68.210205        -0.073676    0.843509
87                   Portugal                 88.0                 5.102               0.87519          0.13719     0.01078                5.9109             72.402023        -0.220714    0.892630
88                     Latvia                 89.0                 5.098               0.72437          0.18226     0.06332                5.9500             66.807465        -0.186889    0.795580
89                Philippines                 90.0                 5.073               0.58114          0.24991     0.12279                6.0060             61.926762        -0.105463    0.733634
90          Somaliland region                 91.0                 5.057               0.43873          0.50318     0.39928                   NaN                   NaN              NaN         NaN
91                    Morocco                 92.0                 5.013               0.60954          0.07172     0.08546                5.0948             65.896240        -0.240377    0.815725
92                  Macedonia                 93.0                 5.007               0.73545          0.22359     0.05327                5.1598             67.504425        -0.019877    0.897491
93                 Mozambique                 94.0                 4.971               0.09131          0.22269     0.15603                4.6236             54.205822         0.032376    0.683019
94                    Albania                 95.0                 4.959               0.81325          0.14272     0.06413                4.8827             68.708138        -0.042309    0.896304
95     Bosnia and Herzegovina                 96.0                 4.949               0.79081          0.24808     0.00227                5.6741             67.808136         0.098275    0.933769
96                    Lesotho                 97.0                 4.898               0.07612          0.16388     0.12504                3.6528             48.003624        -0.145732    0.857392
97         Dominican Republic                 98.0                 4.885               0.66825          0.21684     0.14234                5.6892             65.807487        -0.131263    0.756000
98                       Laos                 99.0                 4.876               0.54909          0.42192     0.24249                4.8886             58.709923         0.111371    0.634679
99                   Mongolia                100.0                 4.874               0.60268          0.33230     0.02666                5.4562             62.304485         0.098094    0.863511

In [26]:
# connect to postgres sql server and database via sql alchemy

engine = create_engine(key, echo=False)
connection = engine.connect()

In [27]:
# get table names

engine.table_names()

['happiness_2015', 'happiness_2020']

In [28]:
# load 2015 dataframe into postgresql database

dropped2015_ordered.to_sql(name='happiness_2015', con=engine, if_exists='append', index=False)

In [29]:
# load 2020 dataframe into postgresql database

dropped2020_transformed.to_sql(name='happiness_2020', con=engine, if_exists='append', index=False)

In [30]:
# confirm data has been loaded into 2015 happiness table

pd.read_sql_query('select * from happiness_2015', con=engine).head()

       country  happiness_rank_2015  happiness_score_2015  life_expectancy_2015  generosity_2015  trust_2015
0  Switzerland                    1                 7.587               0.94143          0.29678     0.41978
1      Iceland                    2                 7.561               0.94784          0.43630     0.14145
2      Denmark                    3                 7.527               0.87464          0.34139     0.48357
3       Norway                    4                 7.522               0.88521          0.34699     0.36503
4       Canada                    5                 7.427               0.90563          0.45811     0.32957

In [31]:
# confirm data has been loaded into 2020 happiness table

pd.read_sql_query('select * from happiness_2020', con=engine).head()

       country  happiness_score_2020  life_expectancy_2020  generosity_2020  trust_2020
0      Finland                7.8087             71.900825        -0.059482    0.195445
1      Denmark                7.6456             72.402504         0.066202    0.168489
2  Switzerland                7.5599             74.102448         0.105911    0.303728
3      Iceland                7.5045             73.000000         0.246944    0.711710
4       Norway                7.4880             73.200783         0.134533    0.263218